version: "3.8"

services:
  PSQL:
    container_name: PSQL
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: qwerty
    networks:
      - mynet

  MONGO:
    container_name: MONGO
    image: mongo:5
    networks:
      - mynet

  calculator:
    build:  ./docker/calculator
    container_name: CALC
    environment:
      PSQL_CONTAINER: "PSQL"
      PSQL_PASS: "qwerty"
      PSQL_USER: "postgres"
      MONGO_CONTAINER: "MONGO"
    ports:
      - 4969:4969
    networks:
      - mynet

  reader:
    container_name: Reader
    build: ./docker/reader
    environment:
      PSQL_CONTAINER: "PSQL"
      PSQL_PASS: "qwerty"
      PSQL_USER: "postgres"
      MONGO_CONTAINER: "MONGO"
    ports:
      - 4979:4979
    networks:
      - mynet

networks:
  mynet:
    name: mynet
    driver: bridge